### ISSUE TITLE
0.3.0 Release

### ISSUE THREAD

**Issue by andrewcoughtrie** [MetOffice/Vernier#137]
- [x] Reporting which callipers and mismatched on fail. #119 outputs the hash, need issue to output the name given to the calliper.
- [x] Finish client MPI communicator #106
- [x] Finish raw wall time #120
- [x] Exception handling #128
- [x] Reformat code to consistent standard
